### ISSUE TITLE
Separate components and API clients

### ISSUE THREAD

**Issue by d-hayashi** [dataware-tools/app-common#48]
## Purpose
Feature request

## Description
コンポーネントとAPIのクライアントを別々のパッケージとして配布したい  
(APIクライアントの更新タイミングが dataware-tools/protocols に依存しており、コンポーネントの更新タイミングとズレているため)

リポジトリを分けると管理が大変になるので、このリポジトリをモノレポ化して `app-common-components` と `app-common-clients` みたいな別々のパッケージで管理すると良いかも

**Comment by WatanabeToshimitsu** [comment]
Resolved by https://github.com/dataware-tools/api-meta-store/pull/56
